import { test } from 'node:test';
import assert from 'node:assert/strict';
import { seed,forecast,safeAuthority,requestAuthorization,travelIntent,execute,revoke,audit,verifyAudit,type Session } from '../lib/covenant/engine.ts';
import { draftPolicy,startAgent,stepAgent,defaultInstruction,callTool } from '../lib/covenant/agent.ts';
async function active(){const s=seed();await draftPolicy(s,defaultInstruction,'fixture',{});s.policy={...s.draft!,confirmed:true};s.draft=null;return s;}
function intent(s:Session,amount:number){const i=travelIntent(s,'safe');return{...i,amount,cart:[{description:'Travel',category:'transportation' as const,amount}]};}
test('exact boundary passes; one cent above fails',async()=>{const a=await active();assert.equal(safeAuthority(a),20000);assert.equal((await requestAuthorization(a,intent(a,20000))).decision,'APPROVED');const b=await active();assert.equal((await requestAuthorization(b,intent(b,20001))).code,'FORWARD_LIQUIDITY_VIOLATION');});
test('unsafe premium denies, safe itinerary passes exact forward minima',async()=>{const s=await active();const d=await requestAuthorization(s,travelIntent(s,'premium'));assert.equal(d.decision,'DENIED');assert.equal(d.forecasts[1].minimum,132000);assert.deepEqual(d.disclosure,{safe_budget_band:{min:15000,max:20000},message:'Upper end is a safe ceiling, not a promise to authorize.'});const a=await requestAuthorization(s,travelIntent(s,'safe'));assert.equal(a.forecasts[1].minimum,151500);assert.equal(a.decision,'APPROVED');});
test('later income cannot mask an earlier rent trough',async()=>{const s=await active();assert.equal(forecast(s)[0].minimum,170000);assert.equal(forecast(s)[0].points.at(-1)!.balance,237500);});
test('certain income counts; uncertain income excluded; delayed scenario still constrains',async()=>{const s=await active();s.accounts[0].balance=160000;s.events=[{name:'Pay',amount:100000,day:1,account_id:'checking',confidence_bps:10000},{name:'Bill',amount:-60000,day:3,account_id:'checking',confidence_bps:10000}];const f=forecast(s);assert.equal(f[0].minimum,160000);assert.equal(f[2].minimum,100000);assert.equal(safeAuthority(s),0);s.events[0].confidence_bps=7500;assert.equal(forecast(s)[1].minimum,100000);});
test('multiple, pending and recurring obligations reduce all future balances',async()=>{const s=await active();s.events.push({name:'Pending',amount:-5000,day:0,account_id:'checking',confidence_bps:5000,pending:true},{name:'Utility',amount:-2000,day:6,account_id:'checking',confidence_bps:10000,recurring_days:10});assert.equal(forecast(s)[1].minimum,159000);assert.equal(safeAuthority(s),9000);});
test('split purchases aggregate across reservations independently of velocity',async()=>{const s=await active();for(let n=0;n<4;n++){s.attempts=[];assert.equal((await requestAuthorization(s,intent(s,5000))).decision,'APPROVED');}assert.equal(safeAuthority(s),0);s.attempts=[];assert.equal((await requestAuthorization(s,intent(s,5000))).decision,'DENIED');});
test('executing converts reservation to cash debit exactly once and preserves exposure',async()=>{const s=await active();const pi=intent(s,5000);await requestAuthorization(s,pi);const a=s.authorizations[0];assert.equal(safeAuthority(s),15000);await execute(s,a.token,pi);assert.equal(s.accounts[0].balance,285000);assert.equal(safeAuthority(s),15000);assert.equal(s.receipts.length,1);await assert.rejects(execute(s,a.token,pi),/USED_OR_REVOKED/);});
test('aggregate policy cap counts executed and reserved purchases',async()=>{const s=await active();s.policy!.max_total_spend=6000;const p=intent(s,5000);await requestAuthorization(s,p);await execute(s,s.authorizations[0].token,p);assert.equal((await requestAuthorization(s,intent(s,1001))).code,'AGGREGATE_SPEND_LIMIT');});
test('velocity limited to three intents per ten minutes',async()=>{const s=await active();for(let i=0;i<3;i++)await requestAuthorization(s,intent(s,1));assert.equal((await requestAuthorization(s,intent(s,1))).code,'VELOCITY_LIMIT');});
test('expires at exact boundary; expired reservations release authority',async()=>{const s=await active();const p=intent(s,5000);await requestAuthorization(s,p);const a=s.authorizations[0];await assert.rejects(execute(s,a.token,p,s.agent.id,a.expires_at),/EXPIRED/);assert.equal(safeAuthority(s,'checking',a.expires_at),20000);});
test('all critical transaction fields are hash bound',async()=>{const changes=[{merchant:'Other'},{amount:5001,cart:[{description:'Travel',category:'transportation',amount:5001}]},{purpose:'Other'},{cart:[{description:'Different cart',category:'transportation',amount:5000}]}];for(const change of changes){const s=await active(),p=intent(s,5000);await requestAuthorization(s,p);await assert.rejects(execute(s,s.authorizations[0].token,{...p,...change}),/BINDING_MISMATCH/);}const s=await active(),p=intent(s,5000);await requestAuthorization(s,p);await assert.rejects(execute(s,s.authorizations[0].token,{...p,currency:'EUR'}));});
test('revoked policy, agent and token block execution immediately',async()=>{for(const scope of ['policy','agent','authorization'] as const){const s=await active(),p=intent(s,5000);await requestAuthorization(s,p);const a=s.authorizations[0];await revoke(s,scope,a.id);await assert.rejects(execute(s,a.token,p),/REVOKED/);}});
test('no debt, unconfirmed, category, agent, duplicate and expiry checks',async()=>{const s=await active();const p=intent(s,100);assert.equal((await requestAuthorization(s,{...p,creates_debt:true})).code,'NEW_DEBT_PROHIBITED');s.attempts=[];assert.equal((await requestAuthorization(s,p)).code,'DUPLICATE_INTENT');const s2=await active();s2.policy!.confirmed=false;assert.equal((await requestAuthorization(s2,intent(s2,100))).code,'POLICY_NOT_CONFIRMED');const s3=await active();s3.policy!.allowed_categories=['lodging'];assert.equal((await requestAuthorization(s3,intent(s3,100))).code,'CATEGORY_PROHIBITED');const s4=await active();assert.equal((await requestAuthorization(s4,{...intent(s4,100),agent_id:'other'})).code,'AGENT_REVOKED_OR_MISMATCH');const s5=await active();s5.policy!.expires_at=0;assert.equal((await requestAuthorization(s5,intent(s5,100))).code,'POLICY_REVOKED_OR_EXPIRED');});
test('negative cash and nonspendable accounts cannot rescue checking',async()=>{const s=await active();s.accounts[0].balance=-100;s.accounts.push({id:'savings',name:'Restricted savings',balance:10000000,currency:'USD',debt:0,credit_available:0});assert.equal(safeAuthority(s),0);assert.equal(forecast(s)[1].minimum,-120100);assert.equal((await requestAuthorization(s,intent(s,1))).code,'FORWARD_LIQUIDITY_VIOLATION');assert.equal(forecast(s,'savings')[1].minimum,10000000);});
test('malformed amounts and inconsistent cart sums cannot request credentials',async()=>{const s=await active();for(const amount of [-1,1.1,0])await assert.rejects(requestAuthorization(s,intent(s,amount)));const pi=intent(s,5000);await assert.rejects(requestAuthorization(s,{...pi,amount:6000}));assert.equal(s.authorizations.length,0);});
test('payment rechecks state deterioration; wrong agent blocked',async()=>{const s=await active(),p=intent(s,5000);await requestAuthorization(s,p);const a=s.authorizations[0];await assert.rejects(execute(s,a.token,p,'intruder'),/AGENT/);s.accounts[0].balance=200000;await assert.rejects(execute(s,a.token,p),/STATE_CHANGED/);assert.equal(s.receipts.length,0);});
test('audit verifies and detects edited, deleted, reordered entries',async()=>{const s=await active();await audit(s,'ONE',{a:1});await audit(s,'TWO',{a:2});assert.equal(await verifyAudit(s.audit),true);const copy=structuredClone(s.audit);copy[1].data={a:3};assert.equal(await verifyAudit(copy),false);assert.equal(await verifyAudit(s.audit.slice(1)),false);});
test('fixture controller completes real tool-engine loop without pretending model usage',async()=>{const s=await active();await startAgent(s,'fixture');for(let i=0;i<16&&String(s.agent.status)==='running';i++)await stepAgent(s,{});assert.equal(s.agent.status,'complete');assert.equal(s.receipts.length,1);assert.equal(s.receipts[0].amount,18500);assert.deepEqual(s.decisions.map(d=>d.decision),['DENIED','APPROVED']);assert.equal(await verifyAudit(s.audit),true);assert.equal(s.audit.some(a=>a.type==='MODEL_TURN'),false);});
test('agent sees bounded disclosure rather than account data',async()=>{const s=await active();await callTool(s,'request_authorization',{option_id:'premium'});const result=await callTool(s,'inspect_authorization_failure',{});assert.ok(!JSON.stringify(result).includes('132000'));const constraints=await callTool(s,'get_policy_constraints',{});assert.ok(!JSON.stringify(constraints).includes('290000'));});
test('draft never establishes authority and ambiguous fixture instructions are rejected',async()=>{const s=seed();await draftPolicy(s,defaultInstruction,'fixture',{});assert.equal(s.policy,null);await assert.rejects(startAgent(s,'fixture'),/Confirm/);await assert.rejects(draftPolicy(s,'spend whatever you want','fixture',{}),/Fixture mode/);});

test('financial shock invalidates approved authority and model tools receive new bounded budget',async()=>{const s=await active();await startAgent(s,'fixture',true);for(let i=0;i<16&&String(s.agent.status)==='running';i++)await stepAgent(s,{});assert.equal(s.agent.status,'paused');assert.equal(s.authorizations.find(a=>a.status==='active')!.intent.amount,18500);const {injectObligation}=await import('../lib/covenant/evaluation.ts');await injectObligation(s,10000);for(let i=0;i<16&&String(s.agent.status)==='running';i++)await stepAgent(s,{});assert.equal(s.agent.status,'complete');assert.equal(s.receipts[0].amount,9500);assert.equal(s.receipts[0].forecasts[1].minimum,150500);assert.equal(s.authorizations.filter(a=>a.status==='revoked').length,1);assert.equal(s.audit.some(a=>a.type==='AUTHORIZATION_INVALIDATED'),true);assert.equal(await verifyAudit(s.audit),true);});
test('infeasible shock stops with no payment and never weakens the reserve',async()=>{const s=await active();await startAgent(s,'fixture',true);for(let i=0;i<16&&String(s.agent.status)==='running';i++)await stepAgent(s,{});const {injectObligation}=await import('../lib/covenant/evaluation.ts');await injectObligation(s,15000);for(let i=0;i<16&&String(s.agent.status)==='running';i++)await stepAgent(s,{});assert.equal(s.agent.status,'stopped');assert.equal(s.receipts.length,0);assert.equal(s.accounts[0].balance,290000);assert.equal(s.policy!.min_liquidity,150000);});
test('paired deterministic evaluation exposes static-cap unsafe approvals without claiming a model benchmark',async()=>{const {runEvaluation}=await import('../lib/covenant/evaluation.ts');const e=await runEvaluation();assert.equal(e.summary.cases,8);assert.equal(e.summary.passed,8);assert.equal(e.summary.baseline_unsafe_approvals,5);assert.equal(e.summary.covenant_unsafe_approvals,0);});
test('pre-payment checkpoint blocks additional tools in the same model turn',async()=>{const s=await active();await startAgent(s,'fixture',true);await callTool(s,'request_authorization',{option_id:'safe'});assert.equal(s.agent.status,'paused');const result:any=await callTool(s,'execute_authorized_purchase',{authorization_id:s.authorizations[0].id});assert.equal(result.error,'CHECKPOINT_PAUSED');await callTool(s,'finish_task',{summary:'claimed complete'});assert.equal(s.agent.status,'paused');assert.equal(s.receipts.length,0);});

test('receipt records fresh execution forecast when a smaller new bill still passes',async()=>{const s=await active(),p=travelIntent(s,'safe');await requestAuthorization(s,p);s.events.push({name:'Small new bill',amount:-500,day:7,account_id:'checking',confidence_bps:10000});await execute(s,s.authorizations[0].token,p);assert.equal(s.authorizations[0].decision.forecasts[1].minimum,151500);assert.equal(s.receipts[0].forecasts[1].minimum,151000);});


test('checking plus monthly card setup reserves statement once, grants no authority, and survives reset',async()=>{
  const {completeSetup,resetDemo}=await import('../lib/covenant/setup.ts');
  const s=seed();await completeSetup(s,'checking_card',123456);
  assert.equal(s.accounts[0].balance,350000);assert.equal(s.accounts[1].debt,60000);
  assert.equal(s.events.filter(e=>e.name.includes('card')).length,1);
  assert.equal(forecast(s)[1].minimum,170000);assert.equal(s.policy,null);assert.equal(s.draft,null);
  await assert.rejects(startAgent(s,'fixture'),/Confirm/);
  await draftPolicy(s,defaultInstruction,'fixture',{});s.policy={...s.draft!,confirmed:true};s.draft=null;
  assert.equal(safeAuthority(s),20000);
  const next=resetDemo(s);assert.deepEqual(next.onboarding,s.onboarding);assert.equal(next.accounts[0].balance,350000);
  assert.equal(next.policy,null);assert.equal(next.receipts.length,0);assert.equal(next.events.filter(e=>e.name.includes('card')).length,1);
  assert.equal(await verifyAudit(s.audit),true);
});
test('setup cannot replace confirmed or drafted rules and cannot erase active reservations',async()=>{
  const {completeSetup}=await import('../lib/covenant/setup.ts');
  const s=await active();const before=JSON.stringify(s);
  await assert.rejects(completeSetup(s,'checking_card'),/Reset/);assert.equal(JSON.stringify(s),before);
  const draft=seed();await draftPolicy(draft,defaultInstruction,'fixture',{});
  await assert.rejects(completeSetup(draft,'checking_card'),/Reset/);
  const booked=await active();await requestAuthorization(booked,travelIntent(booked,'safe'));booked.policy=null;
  await assert.rejects(completeSetup(booked,'checking_only'),/Reset/);
});
test('checking-card journey replans after a new bill and includes the existing card payment in receipt',async()=>{
  const {completeSetup}=await import('../lib/covenant/setup.ts');
  const {injectObligation}=await import('../lib/covenant/evaluation.ts');
  const s=seed();await completeSetup(s,'checking_card');await draftPolicy(s,defaultInstruction,'fixture',{});
  s.policy={...s.draft!,confirmed:true};s.draft=null;await startAgent(s,'fixture',true);
  for(let i=0;i<16&&String(s.agent.status)==='running';i++)await stepAgent(s,{});
  assert.equal(s.agent.status,'paused');await injectObligation(s,10000);
  for(let i=0;i<16&&String(s.agent.status)==='running';i++)await stepAgent(s,{});
  assert.equal(s.agent.status,'complete');assert.equal(s.receipts[0].amount,9500);
  assert.equal(s.receipts[0].forecasts[1].minimum,150500);
  assert.equal(s.receipts[0].events!.filter(e=>e.name.includes('card')).length,1);
  assert.equal(s.accounts[0].balance,340500);assert.equal(await verifyAudit(s.audit),true);
});
