import { z } from 'zod';
const cents=z.number().int().nonnegative().max(1000000000);
export const policySchema=z.object({purpose:z.literal('conference_travel'),max_total_spend:cents,min_liquidity:cents,forecast_horizon_days:z.number().int().min(5).max(90),allow_new_debt:z.boolean(),allowed_categories:z.array(z.enum(['transportation','lodging','local_transit'])).min(1),disclosure_level:z.enum(['exact','bounded','binary'])}).strict();
export type Policy=z.infer<typeof policySchema>&{id:string;confirmed:boolean;revoked:boolean;expires_at:number};
export const intentSchema=z.object({intent_id:z.string().min(1).max(100),agent_id:z.string().min(1).max(100),policy_id:z.string().min(1).max(100),account_id:z.string(),merchant:z.string().min(1).max(120),amount:cents.refine(v=>v>0),currency:z.literal('USD'),purpose:z.string().min(1).max(200),creates_debt:z.boolean(),cart:z.array(z.object({description:z.string().min(1).max(150),amount:cents,category:z.enum(['transportation','lodging','local_transit'])}).strict()).min(1).max(20)}).strict().refine(v=>v.cart.reduce((s,i)=>s+i.amount,0)===v.amount,'Cart must equal amount');
export type Intent=z.infer<typeof intentSchema>;
export type Event={name:string;account_id:string;amount:number;day:number;confidence_bps:number;pending?:boolean;recurring_days?:number};
export type Forecast={scenario:string;minimum:number;points:{day:number;balance:number;name:string}[]};
export type Decision={decision:'APPROVED'|'DENIED';code:string;intent:Intent;forecasts:Forecast[];safe_amount:number;disclosure:unknown;authorization_id?:string;intent_hash?:string};
export type Audit={id:string;type:string;time:number;data:unknown;previous_hash:string;hash:string};
export type Authorization={id:string;token:string;intent:Intent;hash:string;expires_at:number;status:'active'|'used'|'revoked';decision:Decision;balance_before:number};
export type Receipt={id:string;amount:number;intent:Intent;authorization:Omit<Authorization,'token'>;forecasts:Forecast[];policy:Policy;balance_before:number;balance_after:number;liquidity_floor:number;events?:Event[];time:number;audit_hash:string};
export type Session={accounts:{id:string;name:string;balance:number;currency:'USD';debt:number;credit_available:number}[];events:Event[];policy:Policy|null;draft:Policy|null;authorizations:Authorization[];attempts:number[];decisions:Decision[];receipts:Receipt[];audit:Audit[];agent:{id:string;revoked:boolean;status:'idle'|'running'|'paused'|'complete'|'stopped'|'error';mode:'fixture'|'live';steps:number;messages:any[];summary:string};clock:string;onboarding?:{completed_at:number;scenario:'checking_card'|'checking_only'};challenge?:{pause_before_payment:boolean;paused_once:boolean;shock_amount:number};evaluation?:unknown;last_failure:unknown};
export function seed():Session{return{accounts:[{id:'checking',name:'Checking / DEMO-001',balance:290000,currency:'USD',debt:0,credit_available:0}],events:[{name:'Rent',account_id:'checking',amount:-120000,day:5,confidence_bps:10000},{name:'Expected paycheck',account_id:'checking',amount:90000,day:14,confidence_bps:7500}],policy:null,draft:null,authorizations:[],attempts:[],decisions:[],receipts:[],audit:[],agent:{id:'travel_agent_01',revoked:false,status:'idle',mode:'fixture',steps:0,messages:[],summary:''},clock:'2026-10-04',last_failure:null};}
export function canonical(v:any):string{if(v===null||typeof v!=='object')return JSON.stringify(v);if(Array.isArray(v))return '['+v.map(canonical).join(',')+']';return '{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')+'}';}
export async function hash(v:unknown){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(canonical(v)));return Array.from(new Uint8Array(b),v=>v.toString(16).padStart(2,'0')).join('');}
export async function audit(s:Session,type:string,data:unknown,now=Date.now()){const previous_hash=s.audit.at(-1)?.hash??'0'.repeat(64);const entry={id:crypto.randomUUID(),type,time:now,data,previous_hash};const a={...entry,hash:await hash(entry)};s.audit.push(a);return a;}
export async function verifyAudit(entries:Audit[]){let prev='0'.repeat(64);for(const a of entries){const {hash:expected,...body}=a;if(body.previous_hash!==prev||await hash(body)!==expected)return false;prev=expected;}return true;}
export function commitment(s:Session,accountId:string,now=Date.now()){return s.authorizations.filter(a=>a.status==='active'&&a.expires_at>now&&a.intent.account_id===accountId).reduce((t,a)=>t+a.intent.amount,0);}
export function forecast(s:Session,accountId='checking',amount=0,horizon=s.policy?.forecast_horizon_days??30,now=Date.now()):Forecast[]{const a=s.accounts.find(a=>a.id===accountId);if(!a)throw Error('UNKNOWN_ACCOUNT');return ['expected','conservative','delayed-income'].map(scenario=>{let balance=a.balance-commitment(s,accountId,now)-amount;const points=[{day:0,balance,name:amount?'Proposed purchase':'Now'}];let minimum=balance;const events=s.events.filter(e=>e.account_id===accountId).flatMap(e=>{const all=[e];if(e.recurring_days)for(let day=e.day+e.recurring_days;day<=horizon;day+=e.recurring_days)all.push({...e,day});return all;}).map(e=>({...e,day:e.day+(e.amount>0&&scenario==='delayed-income'?7:0)})).filter(e=>e.day>=0&&e.day<=horizon).sort((a,b)=>a.day-b.day||a.amount-b.amount);for(const e of events){let value=e.amount;if(value>0){if(scenario==='conservative'&&e.confidence_bps<10000)value=0;else if(scenario==='expected')value=Math.floor(value*e.confidence_bps/10000);}balance+=value;minimum=Math.min(minimum,balance);points.push({day:e.day,balance,name:e.name});}points.push({day:horizon,balance,name:'Horizon'});return{scenario,minimum,points};});}
export function safeAuthority(s:Session,accountId='checking',now=Date.now()){if(!s.policy)return 0;const used=s.receipts.filter(r=>r.policy.id===s.policy!.id).reduce((v,r)=>v+r.amount,0);const reserved=s.authorizations.filter(a=>a.status==='active'&&a.expires_at>now&&a.intent.policy_id===s.policy!.id).reduce((v,a)=>v+a.intent.amount,0);const min=Math.min(...forecast(s,accountId,0,s.policy.forecast_horizon_days,now).filter(f=>f.scenario!=='expected').map(f=>f.minimum));return Math.max(0,Math.min(s.policy.max_total_spend-used-reserved,min-s.policy.min_liquidity));}
export function disclosed(s:Session,safe:number){if(s.policy?.disclosure_level==='binary')return{message:'Reduce cost and retry'};if(s.policy?.disclosure_level==='exact')return{safe_maximum:safe};const max=Math.floor(safe/5000)*5000;return{safe_budget_band:{min:Math.max(0,max-5000),max},message:'Upper end is a safe ceiling, not a promise to authorize.'};}
export async function requestAuthorization(s:Session,raw:unknown,now=Date.now()):Promise<Decision>{const intent=intentSchema.parse(raw);const p=s.policy;const safe=safeAuthority(s,intent.account_id,now);const forecasts=forecast(s,intent.account_id,intent.amount,p?.forecast_horizon_days??30,now);let code='POLICY_PASS';if(!p?.confirmed)code='POLICY_NOT_CONFIRMED';else if(p.revoked||p.expires_at<=now)code='POLICY_REVOKED_OR_EXPIRED';else if(intent.policy_id!==p.id)code='POLICY_MISMATCH';else if(s.agent.revoked||intent.agent_id!==s.agent.id)code='AGENT_REVOKED_OR_MISMATCH';else if(s.attempts.filter(t=>t>now-600000).length>=3)code='VELOCITY_LIMIT';else if(s.decisions.some(d=>d.intent.intent_id===intent.intent_id))code='DUPLICATE_INTENT';else if(intent.creates_debt&&!p.allow_new_debt)code='NEW_DEBT_PROHIBITED';else if(intent.cart.some(c=>!p.allowed_categories.includes(c.category)))code='CATEGORY_PROHIBITED';else{const spent=s.receipts.filter(r=>r.policy.id===p.id).reduce((t,r)=>t+r.amount,0);const reserved=s.authorizations.filter(a=>a.status==='active'&&a.expires_at>now&&a.intent.policy_id===p.id).reduce((t,a)=>t+a.intent.amount,0);if(spent+reserved+intent.amount>p.max_total_spend)code='AGGREGATE_SPEND_LIMIT';else if(forecasts.filter(f=>f.scenario!=='expected').some(f=>f.minimum<p.min_liquidity))code='FORWARD_LIQUIDITY_VIOLATION';}
s.attempts.push(now);await audit(s,'PURCHASE_PROPOSED',{intent},now);await audit(s,'FORECAST_EXECUTED',{forecasts},now);const d:Decision={decision:code==='POLICY_PASS'?'APPROVED':'DENIED',code,intent,forecasts,safe_amount:safe,disclosure:disclosed(s,safe)};if(d.decision==='APPROVED'){const id=crypto.randomUUID();const h=await hash(intent);d.authorization_id=id;d.intent_hash=h;const a:Authorization={id,token:'COV_'+crypto.randomUUID(),intent,hash:h,expires_at:now+300000,status:'active',decision:d,balance_before:s.accounts.find(a=>a.id===intent.account_id)!.balance};s.authorizations.push(a);await audit(s,'AUTHORIZATION_APPROVED',{id,intent_hash:h,amount:intent.amount},now);await audit(s,'TOKEN_ISSUED',{id,expires_at:a.expires_at,single_use:true},now);}else{await audit(s,'AUTHORIZATION_DENIED',{code,disclosure:d.disclosure},now);s.last_failure={decision:'DENIED',code,retry_allowed:!['VELOCITY_LIMIT','POLICY_REVOKED_OR_EXPIRED','AGENT_REVOKED_OR_MISMATCH'].includes(code),disclosure:d.disclosure};}s.decisions.push(d);return d;}
export async function execute(s:Session,token:string,raw:unknown,agentId=s.agent.id,now=Date.now()){const intent=intentSchema.parse(raw);const a=s.authorizations.find(a=>a.token===token);if(!a)throw Error('INVALID_CREDENTIAL');if(a.status!=='active')throw Error('CREDENTIAL_USED_OR_REVOKED');if(a.expires_at<=now)throw Error('CREDENTIAL_EXPIRED');if(!s.policy?.confirmed||s.policy.revoked||s.policy.expires_at<=now||s.policy.id!==a.intent.policy_id)throw Error('POLICY_REVOKED_OR_EXPIRED');if(s.agent.revoked||agentId!==a.intent.agent_id)throw Error('AGENT_REVOKED_OR_MISMATCH');if(await hash(intent)!==a.hash)throw Error('TRANSACTION_BINDING_MISMATCH');const account=s.accounts.find(x=>x.id===intent.account_id)!;
// Re-evaluate against current state, accounting for all outstanding reservations exactly once.
const executionForecasts=forecast(s,intent.account_id,0,s.policy.forecast_horizon_days,now);if(executionForecasts.filter(f=>f.scenario!=='expected').some(f=>f.minimum<s.policy!.min_liquidity)){a.status='revoked';s.last_failure={decision:'DENIED',code:'STATE_CHANGED_LIQUIDITY_VIOLATION',retry_allowed:true,disclosure:disclosed(s,safeAuthority(s,intent.account_id,now))};await audit(s,'AUTHORIZATION_INVALIDATED',{authorization_id:a.id,reason:'STATE_CHANGED_LIQUIDITY_VIOLATION',amount:intent.amount,forecasts:executionForecasts,disclosure:(s.last_failure as any).disclosure},now);throw Error('STATE_CHANGED_LIQUIDITY_VIOLATION');}const before=account.balance;account.balance-=intent.amount;a.status='used';const event=await audit(s,'PAYMENT_EXECUTED',{authorization_id:a.id,amount:intent.amount,intent_hash:a.hash,forecasts:executionForecasts},now);const {token:omit,...authorization}=a;void omit;const r:Receipt={id:crypto.randomUUID(),amount:intent.amount,intent,authorization,forecasts:executionForecasts,policy:structuredClone(s.policy),balance_before:before,balance_after:account.balance,liquidity_floor:s.policy.min_liquidity,events:structuredClone(s.events),time:now,audit_hash:event.hash};s.receipts.push(r);return{receipt_id:r.id,status:'EXECUTED',amount:intent.amount};}
export const options=[{id:'premium',name:'Express rail + private room',quality:3,transport:24500,lodging:12000,transit:1500,total:38000},{id:'mid',name:'Regional rail + budget hotel',quality:2,transport:16000,lodging:8500,transit:1500,total:26000},{id:'safe',name:'Coach + hostel + local transit',quality:1,transport:12100,lodging:4900,transit:1500,total:18500},{id:'commuter',name:'Same-day coach + transit; no overnight stay',quality:0,transport:8500,lodging:0,transit:1000,total:9500}];
export function travelIntent(s:Session,optionId:string):Intent{const o=options.find(o=>o.id===optionId);if(!o||!s.policy)throw Error('INVALID_OPTION_OR_POLICY');return{intent_id:crypto.randomUUID(),agent_id:s.agent.id,policy_id:s.policy.id,account_id:'checking',merchant:'HackRail Sandbox',amount:o.total,currency:'USD',purpose:'Conference travel',creates_debt:false,cart:[{description:'Round-trip transportation',amount:o.transport,category:'transportation'},{description:o.lodging?'Lodging reservation':'Same-day trip; no lodging',amount:o.lodging,category:'lodging'},{description:'Local transit',amount:o.transit,category:'local_transit'}]};}
export async function revoke(s:Session,scope:'policy'|'agent'|'authorization',id?:string){if(scope==='policy'&&s.policy)s.policy.revoked=true;if(scope==='agent')s.agent.revoked=true;s.authorizations.filter(a=>a.status==='active'&&(scope!=='authorization'||a.id===id)).forEach(a=>a.status='revoked');if(scope!=='authorization')s.agent.status='stopped';await audit(s,'REVOKED',{scope,id:id??null});}
export function publicState(s:Session){return{...s,authorizations:s.authorizations.map(({token,...a})=>a),agent:{...s.agent,messages:undefined},last_failure:s.last_failure};}
