'use client';
import {useEffect,useState} from 'react';
import type {Session,Forecast} from '@/lib/covenant/engine';
import {minimumCash,purchaseEvidence} from '@/lib/covenant/presentation';
const money=(v:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:v%100?2:0}).format(v/100);
const toolNames:Record<string,string>={get_policy_constraints:'Read your rules',search_travel_options:'Search the travel inventory',request_authorization:'Request permission',inspect_authorization_failure:'Read the safe spending range',execute_authorized_purchase:'Try the final payment check',finish_task:'Finish the task'};
type Props={state:Session;model:string;configured:boolean;recheck?:Forecast[];chainValid:boolean;busy:boolean;attack?:{kind:string;results:{blocked?:boolean;code?:string;decision?:string}[]};onInspect:(index:number)=>void;onAttack:(kind:string)=>void;onEvaluate:()=>void;onPreset:()=>void;onStart:()=>void;onContinue:()=>void;onShock:(amount:string)=>void};
export function AuthorityExperience({state:s,model,configured,recheck,chainValid,busy,attack,onInspect,onAttack,onEvaluate,onPreset,onStart,onContinue,onShock}:Props){
  const [now,setNow]=useState(Date.now);
  useEffect(()=>{const id=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(id);},[]);
  const floor=s.policy?.min_liquidity??s.draft?.min_liquidity??150000;
  const receipt=s.receipts.at(-1);
  const modelTurns=s.audit.filter(a=>a.type==='MODEL_TURN'||a.type==='MODEL_POLICY_DRAFTED');
  const lastTurn=modelTurns.at(-1)?.data as {tools?:string[];model?:string;usage?:{total_tokens?:number};latency_ms?:number}|undefined;
  const lastTool=s.audit.filter(a=>a.type==='AGENT_TOOL_RESULT').at(-1)?.data as {tool?:string;result?:{error?:string;disclosure?:unknown}}|undefined;
  const disclosedBudget=(s.audit.filter(a=>a.type==='AGENT_TOOL_RESULT'&&!!(a.data as {result?:{disclosure?:{safe_budget_band?:unknown}}}).result?.disclosure?.safe_budget_band).at(-1)?.data as {result?:{disclosure?:{safe_budget_band?:{min:number;max:number}}}}|undefined)?.result?.disclosure?.safe_budget_band;
  const tokens=modelTurns.reduce((n,a)=>n+((a.data as {usage?:{total_tokens?:number}}).usage?.total_tokens??0),0);
  const invalidations=s.audit.filter(a=>a.type==='AUTHORIZATION_INVALIDATED');
  const approved=s.authorizations.find(a=>a.status==='active'&&a.expires_at>now);
  const evaluation=s.evaluation as {summary:{cases:number;passed:number;baseline_unsafe_approvals:number;covenant_unsafe_approvals:number}}|undefined;
  const latestAttack=attack??(s.audit.filter(a=>a.type==='CONTROL_TEST_EXECUTED').at(-1)?.data as Props['attack']);
  const preflight=!s.policy&&!s.decisions.length;
  const running=s.agent.status==='running';
  const policyActive=!!s.policy?.confirmed&&!s.policy.revoked&&!s.agent.revoked&&s.policy.expires_at>now;
  const title=receipt?(invalidations.length?'Permission withdrawn. A safer plan executed.':'Final check passed. Purchase executed.'):s.agent.status==='paused'?'Approved for now. Still no payment.':invalidations.length?'The old permission no longer works.':s.agent.status==='stopped'?'The agent stopped without new permission.':running?'Watch the agent earn permission to spend.':'Test what happens between approval and payment.';
  if(preflight)return <section className="challenge-intro" aria-label="Financial authority challenge"><div><span className="eyebrow">The challenge</span><h2>Approve a trip. Add a bill. Watch permission change.</h2><p>A purchase can fit your budget and still threaten your reserve. Run the agent, interrupt it before payment, and inspect what it does next.</p></div><button className="secondary" disabled={busy||!!s.draft} onClick={onPreset}>Use the guided challenge ↗</button></section>;
  return <section className="authority-experience" aria-labelledby="authority-title">
    <div className="authority-heading"><div><span className="eyebrow">Financial authority / observed in this session</span><h2 id="authority-title">{title}</h2></div><span className={`badge ${invalidations.length?'denied':''}`}>{receipt?'Payment checked':s.agent.status==='paused'?'Paused before payment':running?'Agent running':'Rules confirmed'}</span></div>
    {s.agent.status==='paused'&&<div className="authority-challenge"><div><b>Change the financial state before it pays.</b><span>In the guided scenario, $100 forces a cheaper trip; $150 leaves no safe option.</span></div><div className="shock-presets"><button className="primary" disabled={busy} onClick={()=>onShock('100')}>Add $100 bill →</button><button className="secondary" disabled={busy} onClick={()=>onShock('150')}>Add $150 bill →</button><button className="text-button" disabled={busy} onClick={()=>onShock('0')}>Continue without a bill →</button></div></div>}
    {!s.agent.steps&&policyActive&&<div className="authority-start"><button className="primary" disabled={busy} onClick={onStart}>Start agent →</button><span>Pauses before payment when the challenge is enabled below.</span></div>}
    {running&&!busy&&<div className="authority-start"><button className="primary" onClick={onContinue}>Continue agent →</button><span>Resume the recorded session.</span></div>}
    <div className="authority-roles">
      <div><span className="role-number">01</span><div><h3>{!s.agent.steps?'Agent proposes':s.agent.mode==='live'?'Nemotron proposes':'Fixture proposes'}</h3><p>Chooses a trip and requests permission.</p></div></div>
      <div><span className="role-number">02</span><div><h3>COVENANT checks</h3><p>Forecasts bills, income delays, and committed cash.</p></div></div>
      <div><span className="role-number">03</span><div><h3>Payment rechecks</h3><p>Checks again before using the exact purchase permission.</p></div></div>
    </div>
    {s.decisions.length?<div className="purchase-observations"><div className="purchase-table-head"><span>Agent’s proposal</span><span>Trip cap</span><span>Lowest future cash</span><span>Permission now</span></div>{s.decisions.map((d,i)=>{const e=purchaseEvidence(s,d,now);const below=e.minimum<floor;const labels:Record<string,string>={blocked:'Blocked',reserved:'Reserved · not paid',withdrawn:'Withdrawn',paid:'Paid after recheck',expired:'Expired',revoked:'Revoked',unavailable:'Unavailable'};return <button key={d.intent.intent_id} className={`purchase-observation ${['blocked','withdrawn','revoked','expired'].includes(e.status)?'observation-blocked':'observation-safe'}`} onClick={()=>onInspect(i)}><span className="proposal-price"><b>{money(d.intent.amount)}</b><small>{d.intent.cart.some(c=>c.category==='lodging'&&c.amount>0)?'Travel + overnight stay':'Same-day travel'}</small></span><span className="cap-result" data-label="Trip cap"><b>{e.capPassed?'Fits the cap':'Over the cap'}</b><small>Limit {money(s.policy?.max_total_spend??0)}</small></span><span className="minimum-result" data-label="Lowest future cash"><b>{money(e.minimum)}</b><small>{below?`${money(floor-e.minimum)} below reserve`:`${money(e.minimum-floor)} above reserve`}{e.invalidated&&` · was ${money(e.approvalMinimum)}`}</small></span><span className="permission-result" data-label="Permission now"><b>{labels[e.status]} <span aria-hidden="true">↗</span></b><small>{e.status==='withdrawn'?'Changed bills invalidated approval':e.status==='blocked'?d.code.replaceAll('_',' ').toLowerCase():e.status==='reserved'?'Exact cart · one use · expires in '+Math.max(0,Math.ceil((e.permission!.expires_at-now)/1000))+'s':e.status==='paid'?'Fresh forecast passed at payment':'Cannot authorize a payment'}</small></span></button>;})}</div>:<div className="observation-empty"><span className="running-dot" style={{animation:running?undefined:'none'}}/><p>{running?'Waiting for the first purchase proposal. Actual tool calls appear below.':'Start the agent. Each proposed purchase will appear here with its financial checks.'}</p></div>}
    {recheck&&s.challenge?.shock_amount&&minimumCash(recheck)<floor&&!receipt&&<div className="recheck-warning" role="status"><b>The bill changed the answer.</b><span>The approved purchase now leaves {money(minimumCash(recheck))}, below your {money(floor)} reserve. Payment must check again; approval alone cannot pay.</span></div>}
    {(approved||receipt||invalidations.length>0)&&<div className="permission-proof"><span className="eyebrow">Permission is enforced</span><span><b>Exact purchase</b> Merchant, amount and cart are bound together</span><span><b>Single use</b> {receipt?'Used once for the receipt':'One payment only'}</span><span><b>5-minute expiry</b> {approved?'Time remaining shown above':'Each approval expires'}</span><span><b>Audit chain</b> {chainValid?'Verified':'Verification failed'} · {s.audit.length} events</span></div>}
    <div className="model-observation"><div><span className="eyebrow">{modelTurns.length?'Actual model activity':s.agent.mode==='fixture'?'Deterministic controller':'Model activity'}</span><strong>{modelTurns.length?`${modelTurns.length} model call${modelTurns.length===1?'':'s'} · ${tokens.toLocaleString()} tokens`:s.agent.mode==='fixture'?'No model calls in fixture mode':'No model call recorded yet'}</strong><small>{modelTurns.length?`${lastTurn?.model??model} · Nebius Token Factory`:configured?'Live Nemotron is available':'Live inference requires a configured Worker secret'}</small></div><div className="last-tool"><span>{running?'Latest recorded action':'Last recorded action'}</span><b>{lastTool?.tool?toolNames[lastTool.tool]??lastTool.tool:lastTurn?'Draft the financial rules':'Waiting to start'}</b>{lastTurn?.tools?.length?<small>Nemotron selected: {lastTurn.tools.map(t=>toolNames[t]??t).join(' → ')}</small>:null}{lastTurn?.latency_ms!==undefined&&<small>Last completed call: {(lastTurn.latency_ms/1000).toFixed(1)}s</small>}</div></div>
    {disclosedBudget&&<div className="agent-disclosure"><span className="eyebrow">What the agent received</span><b>{money(disclosedBudget.min)}–{money(disclosedBudget.max)} safe spending range</b><span>Account balances and the full bill forecast stayed outside the agent’s tools.</span></div>}
    <details className="boundary-tests"><summary>Try to break the permission <span>Alter the merchant · reuse a token · spend after expiry</span></summary><p>These tests use isolated copies of the financial scenario. Their results do not spend from or modify this session.</p><div className="boundary-buttons">{[['tamper','Change the merchant'],['replay','Reuse a payment token'],['expiry','Pay after expiry'],['split','Split into smaller purchases']].map(([kind,label])=><button className="secondary" key={kind} disabled={busy||!s.policy} onClick={()=>onAttack(kind)}>{label}</button>)}</div>{latestAttack&&<div className="boundary-result" role="status"><b>{latestAttack.results.every(r=>r.blocked===true||r.decision==='DENIED')?'Attempt blocked':latestAttack.kind==='split'?'Aggregate limit enforced':'Inspect test result'}</b><span>{latestAttack.results.map((r,i)=>`${latestAttack.results.length>1?`Attempt ${i+1}: `:''}${r.code??r.decision??(r.blocked?'blocked':'not blocked')}`).join(' · ')}</span></div>}</details>
    <div className="comparison-proof"><div><span className="eyebrow">Reproduce the financial checks</span><p>{evaluation?<><b>{evaluation.summary.passed}/{evaluation.summary.cases} cases match the expected outcome.</b> Cap + current cash: {evaluation.summary.baseline_unsafe_approvals} unsafe approvals. COVENANT: {evaluation.summary.covenant_unsafe_approvals}.</>:'Compare a purchase cap + current cash check with COVENANT across eight supplied financial cases.'}</p><small>Hand-authored regression cases. This baseline does not represent ChatGPT or all payment products.</small></div><button className="text-button" disabled={busy} onClick={onEvaluate}>{evaluation?'Run comparison again ↗':'Run 8-case comparison ↗'}</button></div>
  </section>;
}
