'use client';
import { useState } from 'react';
import { Select,SelectTrigger,SelectValue,SelectContent,SelectItem } from '@/components/ui/select';
import type { DemoScenario } from '@/lib/covenant/setup';

export function CovenantOnboarding({firstUse,busy,error,initialScenario,onComplete,onClose}:{firstUse:boolean;busy:boolean;error:string;initialScenario:DemoScenario;onComplete:(scenario:DemoScenario)=>void;onClose:()=>void}){
  const [step,setStep]=useState(0);
  const [scenario,setScenario]=useState<DemoScenario>(initialScenario);
  const card=scenario==='checking_card';
  const titles=['Keep using your accounts.','Protect what is already spoken for.','Give the agent a job.'];
  return <div className="shell"><header className="topbar"><div className="brand"><span className="mark">⊢</span>COVENANT</div><span className="status">DEMO WALKTHROUGH</span></header><main className="onboarding" aria-labelledby="setup-title"><div className="setup-progress" aria-label={`Step ${step+1} of 3`}>{['Your accounts','Your bills','Your agent'].map((label,i)=><span className={i===step?'current':''} key={label} aria-current={i===step?'step':undefined}>{i+1}. {label}</span>)}</div><div className="eyebrow">{firstUse?'First-time setup':'How it works'} / {step+1} of 3</div><h1 id="setup-title" tabIndex={-1}>{titles[step]}</h1>
    {step===0&&<><p className="setup-lead">COVENANT checks what an AI can safely spend while keeping your upcoming bills covered.</p>{firstUse&&<div className="setup-picker"><label id="scenario-label">Try a familiar situation</label><Select value={scenario} onValueChange={v=>setScenario(v as DemoScenario)} disabled={busy}><SelectTrigger aria-labelledby="scenario-label"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="checking_card">Checking + a card paid monthly</SelectItem><SelectItem value="checking_only">Checking only</SelectItem></SelectContent></Select></div>}<div className="setup-accounts"><div className="setup-account"><span className="eyebrow">Demo checking</span><strong>{card?'$3,500':'$2,900'}</strong><span>Cash available today</span></div>{card&&<div className="setup-account"><span className="eyebrow">Demo credit card</span><strong>$600</strong><span>Statement due in 9 days<br/>Paid in full from checking</span></div>}</div><p className="setup-note">These are fictional accounts. This demo does not connect to your bank or move real money.</p></>}
    {step===1&&<><p className="setup-lead">A bank balance is bigger than the amount you can safely give an agent.</p><div className="setup-math"><div><span>Checking today</span><b>{card?'$3,500':'$2,900'}</b></div><div><span>Rent in 5 days</span><b>−$1,200</b></div>{card&&<div><span>Card payment in 9 days</span><b>−$600</b></div>}<div><span>Your protected reserve</span><b>−$1,500</b></div><div className="total"><span>Available for the agent</span><b>$200</b></div></div><p className="setup-note">The expected paycheck is uncertain, so it cannot rescue this calculation. {card?'The card statement counts once, when checking pays it.':''}</p><p className="setup-note">In a connected version, your normal spending would update the next check as account data arrives. Here, you can simulate a new bill before payment.</p></>}
    {step===2&&<><p className="setup-lead">“Book my conference travel for under $400. Keep $1,500 available for my future bills.”</p><ol className="setup-instructions"><li><b>Review your rules.</b><span>Click Compile policy, then Confirm this policy. Setup alone grants no spending permission.</span></li><li><b>Let the agent find a trip.</b><span>Click Start travel agent. A $380 trip fails the cash check; a $185 trip fits.</span></li><li><b>See it adapt.</b><span>Enable the pause before starting. Add a $100 bill; the agent must find a $95 trip or stop.</span></li></ol><p className="setup-note">The AI plans. COVENANT checks the bills before authorizing and again before paying. Purchases stay simulated.</p></>}
    {error&&<div className="error" role="alert">{error}</div>}<div className="setup-actions">{step>0&&<button className="secondary" disabled={busy} onClick={()=>setStep(step-1)}>Back</button>}{step<2?<button className="primary" disabled={busy} onClick={()=>{setStep(step+1);requestAnimationFrame(()=>document.getElementById('setup-title')?.focus());}}>Continue</button>:<button className="primary" disabled={busy} onClick={()=>firstUse?onComplete(scenario):onClose()}>{busy?'Preparing…':firstUse?'Use demo accounts and set my rules':'Return to my workspace'}</button>}{!firstUse&&<button className="secondary" disabled={busy} onClick={onClose}>Close guide</button>}</div></main></div>;
}
